stages:
  # - build-window
  - build-linux

# build-window:
#   image: mcr.microsoft.com/windows/servercore:ltsc2019
#   stage: build-window

build-linux:
  image: ubuntu:latest
  stage: build-linux
  before_script:
    - apt update -qy
    - apt install -y curl libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 nodejs
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm install 18.16.0
    - corepack enable
    - corepack prepare yarn@stable --activate

  script:
    - yarn install
    - |
      yarn run svelte:build
    - pip install -r requirements.txt
    - pyinstaller --noconfirm Nyanga-Read.spec

  artifacts:
    paths:
      - "dist/"
