stages:
  - build
  - deploy

build-window:
  image: mcr.microsoft.com/windows/servercore:ltsc2019
  tags:
    - windows
  stage: build
  before_script:
    - choco install nodejs --version 18.16.0 --x64 -y
    - choco install dotnet -y
    - choco install python -y
    - refreshenv

  script:
    - npm install
    - |
      npm run svelte:build
    - c:\python311\python.exe -m venv .venv --upgrade-deps
    - .\.venv\Scripts\Activate.ps1
    - pip install -r requirements-win.txt
    - mkdir log
    - New-Item -ItemTyp "File" -Path ".\log\app.log" -Force
    - pyinstaller --noconfirm --distpath nyanga-window Nyanga-Read-windows.spec

  artifacts:
    paths:
      - nyanga-window/

build-ubuntu:
  image: ubuntu:22.04
  stage: build
  before_script:
    - apt update -qy
    - apt install -y curl libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 nodejs python3-venv glib-networking
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - source "$NVM_DIR/nvm.sh"
    - nvm install 18.16.0
    - corepack enable
    - corepack prepare yarn@stable --activate

  script:
    - yarn install
    - |
      yarn run svelte:build

    - python3 -m venv .venv --upgrade-deps
    - source .venv/bin/activate
    - mkdir -p log
    - touch log/app.log
    - pip install -r requirements-linux.txt
    - pyinstaller --noconfirm --distpath nyanga-ubuntu Nyanga-Read-linux.spec

  artifacts:
    paths:
      - nyanga-ubuntu/
pages:
  stage: deploy
  script:
    - mkdir public/
    - cp -R nyanga-ubuntu/ public/
    - cp -R nyanga-window/ public/

  artifacts:
    paths:
      - public/
