name: Build Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build packages on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Load release metafile
        uses: actions/download-artifact@v1
        with:
          name: release_url
      - name: Retrieving URL
        id: get_release_info
        run: |
          value=$(cat release_url/release_url.txt)
          echo "::set-output name=upload_url::$value"
      - name: Version Update
        shell: bash
        run: |
          # Version update steps, same as before...
      - name: Download artifact from createrelease job
        uses: actions/download-artifact@v2
        with:
          name: createrelease-artifact # Replace with the actual name of the artifact you saved in createrelease job
          path: createrelease-artifact # Replace with the actual path to extract the artifact contents
      - name: Build Windows
        run: |
          # Build steps using the artifact contents from createrelease job
          refreshenv
          mkdir log
          New-Item -ItemType "File" -Path ".\log\app.log" -Force
          npm install
          npm run svelte:build
          python -m venv .venv --upgrade-deps
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r scripts/requirements/requirements-win.txt
          pyinstaller --noconfirm --distpath nyanga scripts/specfile/Nyanga-Read-windows.spec
      - name: Release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./nyanga/Nyanga-Read-ubuntu
          asset_name: Nyanga-Read-ubuntu
          asset_content_type: application/octet-stream
