name: Build Windows
on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ['Create Release']
    types:
      - completed

jobs:
  build:
    name: Build packages for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Load release metafile
        uses: actions/download-artifact@v1
        with:
          name: release_url
      - name: Retrieving URL
        id: get_release_info
        shell: bash
        run: |
          value=$(cat release_url/release_url.txt)
          echo "::set-output name=upload_url::$value"
      - name: Build Windows
        run: |
          refreshenv
          mkdir log
          New-Item -ItemType "File" -Path ".\log\app.log" -Force
          npm install
          npm run svelte:build
          python -m venv .venv --upgrade-deps
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements-win.txt
          pyinstaller --noconfirm --distpath nyanga Nyanga-Read-windows.spec
      - name: Release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./nyanga/Nyanga-Read-window.exe
          asset_name: Nyanga-Read-window.exe
          asset_content_type: application/vnd.microsoft.portable-executable
