name: Build Linux
on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ['Create Release']
    types:
      - completed

jobs:
  build:
    name: Build packages for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Load release metafile
        uses: actions/download-artifact@v1
        with:
          name: release_url
      - name: Retrieving URL
        id: get_release_info
        shell: bash
        run: |
          value=$(cat release_url/release_url.txt)
          echo "::set-output name=upload_url::$value"
      - name: Version Update
        shell: bash
        run: |
          VERSION=$(jq -r '.version' package.json)
          RELEASE=$(jq -r '.releaseRef' docs/app/version.json)
          case "$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')" in
            linux)
              OS="linux"
              ;;
            windows)
              OS="windows"
              ;;
            *)
              OS="unknown"
              ;;
          esac
          cat << EOF > docs/app/version.json
          {
            "currentVersion": "$VERSION",
            "releaseRef": "$RELEASE",
            "os": "$OS"
          }
          EOF
          case "$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')" in
            linux)
              echo "OS=linux" >> $GITHUB_ENV
              ;;
            windows)
              echo "OS=windows" >> $GITHUB_ENV
              ;;
            *)
              echo "OS=unknown" >> $GITHUB_ENV
              ;;
          esac
          echo "{\"version\": \"$VERSION\"}" > release.$OS.json
      - name: Release meta
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: release.${{ env.OS }}.json
          asset_name: release.${{ env.OS }}.json
          asset_content_type: application/json
      - name: Build Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 nodejs python3-venv glib-networking
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm install 18.16.0
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install
          yarn run svelte:build
          python3 -m venv .venv --upgrade-deps
          source .venv/bin/activate
          mkdir -p log
          touch log/app.log
          python -m pip install --upgrade pip
          pip install -r requirements-linux.txt
          pyinstaller --noconfirm --distpath nyanga Nyanga-Read-ubuntu.spec
      - name: Release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./nyanga/Nyanga-Read-ubuntu
          asset_name: Nyanga-Read-ubuntu
          asset_content_type: application/octet-stream
