name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  createrelease:
    name: Create Release
    runs-on: [ubuntu-latest]
    steps:
      - name: Initial step
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Output metafile
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - name: Save metafile
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt
